---
- hosts: all
  become: true
  tasks:
    - name: Install Apache and PHP packages on RHEL
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
